version: '3'

services:
  traefik:
    image: "traefik:v2.0.0-rc4"
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8200"
    ports:
      - "8280:8200"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  consul:
    build: 
      context: ./consul-1.5.2/
      dockerfile: Dockerfile
    container_name: consul
    volumes:
      - "./extras/consul-vault-policy.hcl:/consul/vault-policy.hcl"
      - "./consul-volume:/consul/data/"
        #    networks:
        #      - consul-network
    restart: always
    ports: 
      - "8300"
      - "8301"
      - "8302"
      - "8500"
      - "8600"

  vault:
    build:
      context: ./vault-1.1.3/
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200"
      - "8302"
      - "8500"
      - "8600"
    restart: always
    environment: 
    - VAULT_CACERT=/vault/data/certs/cfssl/selfsigned.pem
    - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
        #    networks:
        #      - vault-network
    volumes:
      - "./extras/dbPolicy.hcl:/var/dbPolicy.hcl"
      - "./vault-volume:/vault/data/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.local`)"
      - "traefik.http.routers.vault.entrypoints=web"

  mysql:
    image: mysql:5.7.26
    container_name: mysql
    volumes:
      - "./extras/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    expose:
      - "3306"

        #networks:
        #  consul-network:
        #  vault-network:
