version: '3'

services:
  consul:
    build: 
      context: ./consul-1.5.2/
      dockerfile: Dockerfile
    volumes:
      - "./extras/consul-vault-policy.hcl:/consul/vault-policy.hcl"
      - "./consul-volume:/consul/data/"
        #    networks:
        #      - consul-network
    restart: always
    ports: 
      - "8300"
      - "8301"
      - "8302"
      - "8500"
      - "8600"

  vault:
    build:
      context: ./vault-1.1.3/
      dockerfile: Dockerfile
    ports:
      - "8200"
      - "8302"
      - "8500"
      - "8600"
    restart: always
    environment: 
    - VAULT_CACERT=/vault/data/certs/cfssl/selfsigned.pem
    - VAULT_ADDR=https://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
        #    networks:
        #      - vault-network
    volumes:
      - "./extras/dbPolicy.hcl:/var/dbPolicy.hcl"
      - "./vault-volume:/vault/data/"

  mysql:
    image: mysql:5.7.26
    volumes:
      - "./extras/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    expose:
      - "3306"

        #networks:
        #  consul-network:
        #  vault-network:
